// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Xs$MyFirstApp from "./Xs.bs.js";
import * as Lemni$MyFirstApp from "./Lemni.bs.js";

function propsToJs(param) {
  return {
          name: param[/* name */0]
        };
}

function propsFromJs(param) {
  return /* record */[/* name */param.name];
}

function stateToJs(param) {
  return {
          count: param[/* count */0],
          label: param[/* label */1]
        };
}

function stateFromJs(param) {
  return /* record */[
          /* count */param.count,
          /* label */param.label
        ];
}

function adaptReducer(reducer, jsState) {
  return stateToJs(Curry._1(reducer, stateFromJs(jsState)));
}

function adaptView(view, self) {
  var param = self.props;
  var props = /* record */[/* name */param.name];
  var state = stateFromJs(self.state);
  var emitter = function (param) {
    return self.emitter(param);
  };
  return Curry._3(view, props, state, emitter);
}

function countReducer(state) {
  return /* record */[
          /* count */state[/* count */0] + 1 | 0,
          /* label */state[/* label */1]
        ];
}

var reactClass = Lemni$MyFirstApp.make((function () {
        var increment = Xs$MyFirstApp.create(/* () */0);
        return /* record */[
                /* initialState */{
                  count: /* count */0,
                  label: /* label */"Test"
                },
                /* stateReducer */increment.map((function () {
                        return (function (param) {
                            return stateToJs(countReducer(stateFromJs(param)));
                          });
                      })),
                /* view */(function (param) {
                    return adaptView((function (props, state, emitter) {
                                  return React.createElement("div", undefined, props[/* name */0], ": ", String(state[/* count */0]), React.createElement("div", undefined, React.createElement("button", {
                                                      onClick: (function (e) {
                                                          return Curry._1(emitter, increment).signal(e);
                                                        })
                                                    }, state[/* label */1])));
                                }), param);
                  })
              ];
      }));

function make(name, children) {
  return ReasonReact.wrapJsForReason(reactClass, {
              name: name
            }, children);
}

export {
  propsToJs ,
  propsFromJs ,
  stateToJs ,
  stateFromJs ,
  adaptReducer ,
  adaptView ,
  countReducer ,
  reactClass ,
  make ,
  
}
/* reactClass Not a pure module */
