// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Xs$MyFirstApp from "./Xs.bs.js";
import * as Lemni$MyFirstApp from "./Lemni.bs.js";

function countReducer(step, state) {
  return /* record */[
          /* count */state[/* count */0] + step | 0,
          /* label */state[/* label */1]
        ];
}

function component() {
  var increment = Xs$MyFirstApp.create(/* () */0);
  return /* record */[
          /* initialState */(function () {
              return /* record */[
                      /* count */0,
                      /* label */"Test"
                    ];
            }),
          /* stateReducer */increment.map((function () {
                  return (function (param) {
                      return countReducer(1, param);
                    });
                })),
          /* view */(function (_, state) {
              return React.createElement("div", undefined, "Count: ", String(state[/* count */0]), React.createElement("div", undefined, React.createElement("button", {
                                  onClick: (function (e) {
                                      increment.shamefullySendNext(e);
                                      return /* () */0;
                                    })
                                }, state[/* label */1])));
            })
        ];
}

function make(step, _) {
  return Lemni$MyFirstApp.l(component, /* record */[/* step */step]);
}

export {
  countReducer ,
  component ,
  make ,
  
}
/* react Not a pure module */
