// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Xs$MyFirstApp from "./Xs.bs.js";

function l(component, props) {
  var baseComponent = ReasonReact.reducerComponent("Lemni");
  var sources_000 = /* props */Xs$MyFirstApp.create(/* () */0);
  var sources_001 = /* state */Xs$MyFirstApp.create(/* () */0);
  var sources = /* record */[
    sources_000,
    sources_001
  ];
  var sinks = Curry._1(component, sources);
  return /* record */[
          /* debugName */baseComponent[/* debugName */0],
          /* reactClassInternal */baseComponent[/* reactClassInternal */1],
          /* handedOffState */baseComponent[/* handedOffState */2],
          /* willReceiveProps */baseComponent[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var stateReducerListener = /* record */[/* next */(function (reducer) {
                    return Curry._1(self[/* send */3], /* Reduce */[reducer]);
                  })];
              Xs$MyFirstApp.subscribe(stateReducerListener, sinks[/* stateReducer */1]);
              return Curry._1(self[/* onUnmount */4], (function () {
                            return Xs$MyFirstApp.removeListener(stateReducerListener, sinks[/* stateReducer */1]);
                          }));
            }),
          /* didUpdate */(function () {
              sources_000.shamefullySendNext(props);
              return /* () */0;
            }),
          /* willUnmount */baseComponent[/* willUnmount */6],
          /* willUpdate */baseComponent[/* willUpdate */7],
          /* shouldUpdate */baseComponent[/* shouldUpdate */8],
          /* render */(function (self) {
              return Curry._2(sinks[/* view */2], props, self[/* state */1]);
            }),
          /* initialState */sinks[/* initialState */0],
          /* retainedProps */baseComponent[/* retainedProps */11],
          /* reducer */(function (action, state) {
              return /* Update */Block.__(0, [Curry._1(action[0], state)]);
            }),
          /* subscriptions */baseComponent[/* subscriptions */13],
          /* jsElementWrapped */baseComponent[/* jsElementWrapped */14]
        ];
}

export {
  l ,
  
}
/* ReasonReact Not a pure module */
