// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as App$MyFirstApp from "./App.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$MyFirstApp.make(2, /* array */[])), "app");

export {
  
}
/*  Not a pure module */
