// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Xstream from "xstream";

function listenerToJs(param) {
  return {
          next: param[/* next */0]
        };
}

function listenerFromJs(param) {
  return /* record */[/* next */param.next];
}

function create() {
  return Xstream.default.create();
}

function streamOf(a) {
  return Curry._1(Xstream.default["of"], a);
}

function subscribe(listener, s) {
  s.subscribe(listenerToJs(listener));
  return /* () */0;
}

function removeListener(listener, s) {
  s.removeListener(listenerToJs(listener));
  return /* () */0;
}

export {
  listenerToJs ,
  listenerFromJs ,
  create ,
  streamOf ,
  subscribe ,
  removeListener ,
  
}
/* xstream Not a pure module */
