// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Xstream from "xstream";

function create() {
  return Xstream.default.create();
}

function streamOf(a) {
  return Curry._1(Xstream.default["of"], a);
}

function subscribe(next, s) {
  s.subscribe({
        next: Curry.__1(next)
      });
  return /* () */0;
}

export {
  create ,
  streamOf ,
  subscribe ,
  
}
/* xstream Not a pure module */
